# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PHP-Perlinfo
version:      0.10
version_from: 
installdirs:  site
requires:
    App::Info:                     0
    File::Which:                   0
    IO::Stringy:                   0
    Module::CoreList:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
